#!/usr/bin/env bash
#10-process_and_pid_file

echo "$$" > /var/run/myscript.pid
trap " echo 'I hate the kill command'; rm /var/run/myscript.pid; exit" SIGTERM
trap "rm /var/run/muscript.pid; exit" SIGQUIT
trap " echo 'Y U no love me?!' " SIGINT

while true; do
echo "To infinity and beyond"
sleep 2
done
